---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2022/6/29 17:33
---
local luaTest = class("luaTest")

function luaTest:Awake()
    print("Awake");
end

return luaTest